### ISSUE TITLE
Do the installation.

### ISSUE THREAD

**Issue by leandroaphermes** [knightzac19/NodeJS-ArkService#2]
Problem when running node index.js start
```
root@ip162:~/node_modules/ark-query-tool# npm install ark-query-tool
npm WARN install Refusing to install ark-query-tool as a dependency of itself
root@ip162:~/node_modules/ark-query-tool# node index.js start

/root/node_modules/ark-query-tool/index.js:1
(function (exports, require, module, __filename, __dirname) { Var arkquery = r
                                                                  ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
root@ip162:~/node_modules/ark-query-tool# npm install
srcds-rcon@2.2.1 node_modules/srcds-rcon

inireader@1.2.0 node_modules/inireader

sourcequery@0.1.2 node_modules/sourcequery
└── smart-buffer@1.0.13
root@ip162:~/node_modules/ark-query-tool# node index.js start

/root/node_modules/ark-query-tool/index.js:46
    return new Promise((r, rj) => {
                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
root@ip162:~/node_modules/ark-query-tool#
```
If possible make a video installation lesson and how to use.

System: Ubuntu server 14.04 64 bits.
method: Arkmanager

**Comment by knightzac19** [comment]
What version of node are you using? It sounds like an old version of node. You need to use node 6+.

**Comment by leandroaphermes** [comment]
Version...

```
root@ip162:~# node -v
v0.10.48
root@ip162:~# npm -v
2.15.1
```

**Comment by leandroaphermes** [comment]
`ot@ip162:~/node_modules/ark-query-tool# node index.js start
Config verification finished!
Initializing Player Data...
Initializing Player Data...
A new API key has been generated:  jpVEft9KiO7f3SQX
Please save the above key as you will not be able to retrieve it!
Doesn't look like bans are in the Linux Folder, going to try the Windows location...
No ban file found, not loading server bans...
No Admins Detected!
Doesn't look like bans are in the Linux Folder, going to try the Windows location...
No ban file found, not loading server bans...
No Admins Detected!
Unhandled rejection ReferenceError: cb is not defined
    at /root/node_modules/ark-query-tool/node_modules/arkdata/lib/playercache.js:121:24
    at next (native)
    at tryCatcher (/root/node_modules/ark-query-tool/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/root/node_modules/ark-query-tool/node_modules/bluebird/js/release/generators.js:97:49)
    at /root/node_modules/ark-query-tool/node_modules/bluebird/js/release/generators.js:201:15
    at /root/node_modules/ark-query-tool/node_modules/steam-webapi/index.js:286:25
    at IncomingMessage.<anonymous> (/root/node_modules/ark-query-tool/node_modules/steam-webapi/index.js:154:28)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Unhandled rejection ReferenceError: cb is not defined
    at /root/node_modules/ark-query-tool/node_modules/arkdata/lib/playercache.js:121:24
    at next (native)
    at tryCatcher (/root/node_modules/ark-query-tool/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/root/node_modules/ark-query-tool/node_modules/bluebird/js/release/generators.js:97:49)
    at /root/node_modules/ark-query-tool/node_modules/bluebird/js/release/generators.js:201:15
    at /root/node_modules/ark-query-tool/node_modules/steam-webapi/index.js:286:25
    at IncomingMessage.<anonymous> (/root/node_modules/ark-query-tool/node_modules/steam-webapi/index.js:154:28)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by leandroaphermes** [comment]
What would this be?  steam_key

```
`{
    "daemon_mode": false,
    "log_console": false,
    "sourcequery": {
        "host": "",
        "port": 27015,
        "rconport": 32330,
        "rconpass": ""
    },
    "server_config": {
        "host": "localhost",
        "port": 8081,
        "use_ajax": true,
        "allowed_server": "http://localhost",
        "ark_path": "/home/hermes/ARK",
        "steam_key": "YOURSTEAMKEY",
        "cache_refresh": 1800000
    },
    "api_settings": {
        "secret": "",
        "hash_type": "sha256"
    }
}`
```

**Comment by knightzac19** [comment]
Yea, you're using v0.10 that's provided by ubuntu. Use this page, https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions to get a more up to date version.

**Comment by knightzac19** [comment]
steam_key is retrieved here, https://steamcommunity.com/login/home/?goto=%2Fdev%2Fapikey

**Comment by leandroaphermes** [comment]
```
node index.js start                                                                                                                                                                                Config verification finished!
Initializing Player Data...
Initializing Player Data...
Doesn't look like bans are in the Linux Folder, going to try the Windows locatio                                                                                                                                                             n...
No ban file found, not loading server bans...
No Admins Detected!
Unhandled rejection ReferenceError: cb is not defined
    at /root/node_modules/ark-query-tool/node_modules/arkdata/lib/playercache.js                                                                                                                                                             :121:24
    at next (native)
    at tryCatcher (/root/node_modules/ark-query-tool/node_modules/bluebird/js/re                                                                                                                                                             lease/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/root/node_modules/ark-query-tool/node_mo                                                                                                                                                             dules/bluebird/js/release/generators.js:97:49)
    at /root/node_modules/ark-query-tool/node_modules/bluebird/js/release/genera                                                                                                                                                             tors.js:201:15
    at /root/node_modules/ark-query-tool/node_modules/steam-webapi/index.js:286:                                                                                                                                                             25
    at ClientRequest.<anonymous> (/root/node_modules/ark-query-tool/node_modules                                                                                                                                                             /steam-webapi/index.js:182:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Doesn't look like bans are in the Linux Folder, going to try the Windows locatio                                                                                                                                                             n...
No ban file found, not loading server bans...
No Admins Detected!
Unhandled rejection ReferenceError: cb is not defined
    at /root/node_modules/ark-query-tool/node_modules/arkdata/lib/playercache.js                                                                                                                                                             :121:24
    at next (native)
    at tryCatcher (/root/node_modules/ark-query-tool/node_modules/bluebird/js/re                                                                                                                                                             lease/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/root/node_modules/ark-query-tool/node_mo                                                                                                                                                             dules/bluebird/js/release/generators.js:97:49)
    at /root/node_modules/ark-query-tool/node_modules/bluebird/js/release/genera                                                                                                                                                             tors.js:201:15
    at /root/node_modules/ark-query-tool/node_modules/steam-webapi/index.js:286:                                                                                                                                                             25
    at ClientRequest.<anonymous> (/root/node_modules/ark-query-tool/node_modules                                                                                                                                                             /steam-webapi/index.js:182:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)


```

**Comment by leandroaphermes** [comment]
Please I really wanted to use this API but I do not know how to instantiate and use: /

Make a video installing and doing some basic commands ... Linux

**Comment by knightzac19** [comment]
There isn't any issue with the API, I'm not providing help for linux here.

**Comment by leandroaphermes** [comment]
Make a video working your API
